services:
  postgres:
    image: postgres:16-alpine
    container_name: whd-postgres
    environment:
      POSTGRES_DB: webhook_delivery
      POSTGRES_USER: whd_user
      POSTGRES_PASSWORD: whd_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: whd-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
